services:
  env-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    container_name: "aspire"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17-alpine"
    container_name: "trakt-db"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "trakt"
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "apphost-e7f9f553c0-postgres-data"
        read_only: false
    networks:
      - "aspire"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U ${POSTGRES_USER} -d trakt"
      interval: "2s"
      timeout: "5s"
      retries: 5
      start_period: "2s"
  bot:
    image: "${BOT_IMAGE}"
    container_name: "bot"
    environment:
      ConnectionStrings__traktdb: "Host=postgres;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=trakt"
      TRAKTDB_HOST: "postgres"
      TRAKTDB_PORT: "5432"
      TRAKTDB_USERNAME: "${POSTGRES_USER}"
      TRAKTDB_PASSWORD: "${POSTGRES_PASSWORD}"
      TRAKTDB_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/trakt"
      TRAKTDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres:5432/trakt"
      TRAKTDB_DATABASENAME: "trakt"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TRAKT_CLIENT_ID: "${TRAKT_CLIENT_ID}"
      TRAKT_CLIENT_SECRET: "${TRAKT_CLIENT_SECRET}"
      TMDB_API_KEY: "${TMDB_API_KEY}"
      ENV: "prod"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/trakt?sslmode=disable"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel_collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "bot"
    depends_on:
      postgres:
        condition: "service_healthy"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  apphost-e7f9f553c0-postgres-data:
    driver: "local"
